version: '3.7'
services:
  postgres:
    container_name: postgres
    restart: always
    build: ./postgres/
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  pgadmin:
    container_name: pgadmin
    restart: always
    build: ./pgadmin/
    ports:
      - 80:80
    environment:
        PGADMIN_DEFAULT_EMAIL: postgres@test.ro
        PGADMIN_DEFAULT_PASSWORD: postgres
    links:
      - postgres